In [46]:
import numpy as np
import pandas as pd

In [47]:
df = pd.read_csv('diabetes.csv')

In [48]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [49]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [50]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [51]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [52]:
X = scaler.fit_transform(X)

In [53]:
X.shape

(768, 8)

In [54]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [55]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [56]:
model = Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [57]:
model.fit(X_train,y_train,batch_size=32,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.3909 - loss: 0.7910 - val_accuracy: 0.4870 - val_loss: 0.7273
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.7163 - val_accuracy: 0.6104 - val_loss: 0.6668
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6466 - loss: 0.6630 - val_accuracy: 0.7013 - val_loss: 0.6216
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6889 - loss: 0.6245 - val_accuracy: 0.7468 - val_loss: 0.5886
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7182 - loss: 0.5942 - val_accuracy: 0.7532 - val_loss: 0.5585
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7362 - loss: 0.5682 - val_accuracy: 0.7857 - val_loss: 0.5378
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7492 - loss: 0.5472 - val_accuracy: 0.7922 - val_loss: 0.5202
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7557 - loss: 0.5305 - val_accuracy: 0.8117 - val_loss: 0.5038
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7557 - loss: 0.5159 - val_accuracy: 0.8117 - val_loss: 0.4923
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7655 - loss: 0.5044 - val_accuracy: 0.8052 - val_loss: 0.4839
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7687 - loss: 0.4952 - val_accuracy: 0.8052 - val_loss: 0.4772
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7671 - loss: 0.4881 - val_accuracy: 0.7922 - val_loss: 0.4717
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4815 - val_accuracy: 0.8052 - val_loss: 0.4673
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4766 - val_accuracy: 0.7987 - val_loss: 0.4642
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4711 - val_accuracy: 0.8052 - val_loss: 0.4607
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4674 - val_accuracy: 0.7987 - val_loss: 0.4595
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4642 - val_accuracy: 0.8117 - val_loss: 0.4577
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4614 - val_accuracy: 0.8052 - val_loss: 0.4561
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4589 - val_accuracy: 0.8117 - val_loss: 0.4563
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4569 - val_accuracy: 0.8052 - val_loss: 0.4553
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4555 - val_accuracy: 0.8117 - val_loss: 0.4559
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4536 - val_accuracy: 0.7987 - val_loss: 0.4549
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4518 - val_accuracy: 0.7987 - val_loss: 0.4557
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4510 - val_accuracy: 0.7922 - val_loss: 0.4551
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4496 - val_accuracy: 0.7922 - val_loss: 0.4555
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4486 - val_accuracy: 0.7922 - val_loss: 0.4555
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4477 - val_accuracy: 0.7922 - val_loss: 0.4564
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4469 - val_accuracy: 0.7987 - val_loss: 0.4557
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4467 - val_accuracy: 0.7987 - val_loss: 0.4556
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4455 - val_accuracy: 0.7987 - val_loss: 0.4553
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4448 - val_accuracy: 0.7987 - val_loss: 0.4556
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4443 - val_accuracy: 0.7922 - val_loss: 0.4549
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4439 - val_accuracy: 0.7922 - val_loss: 0.4543
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4437 - val_accuracy: 0.7987 - val_loss: 0.4527
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4423 - val_accuracy: 0.7987 - val_loss: 0.4529
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4431 - val_accuracy: 0.7987 - val_loss: 0.4522
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4412 - val_accuracy: 0.7987 - val_loss: 0.4527
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4406 - val_accuracy: 0.7987 - val_loss: 0.4538
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4404 - val_accuracy: 0.8052 - val_loss: 0.4535
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4397 - val_accuracy: 0.8052 - val_loss: 0.4541
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4395 - val_accuracy: 0.7987 - val_loss: 0.4537
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4395 - val_accuracy: 0.7987 - val_loss: 0.4519
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4389 - val_accuracy: 0.8052 - val_loss: 0.4517
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4380 - val_accuracy: 0.7987 - val_loss: 0.4516
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4379 - val_accuracy: 0.8052 - val_loss: 0.4502
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4369 - val_accuracy: 0.8052 - val_loss: 0.4506
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4369 - val_accuracy: 0.7987 - val_loss: 0.4523
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4360 - val_accuracy: 0.7987 - val_loss: 0.4516
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4359 - val_accuracy: 0.8052 - val_loss: 0.4516
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4353 - val_accuracy: 0.7987 - val_loss: 0.4521
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4351 - val_accuracy: 0.8052 - val_loss: 0.4525
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4343 - val_accuracy: 0.7987 - val_loss: 0.4528
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4337 - val_accuracy: 0.8052 - val_loss: 0.4533
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4332 - val_accuracy: 0.7987 - val_loss: 0.4541
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4330 - val_accuracy: 0.7987 - val_loss: 0.4545
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4329 - val_accuracy: 0.8052 - val_loss: 0.4541
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4328 - val_accuracy: 0.8052 - val_loss: 0.4528
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4318 - val_accuracy: 0.8117 - val_loss: 0.4535
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4313 - val_accuracy: 0.8182 - val_loss: 0.4536
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4308 - val_accuracy: 0.8117 - val_loss: 0.4544
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4305 - val_accuracy: 0.8052 - val_loss: 0.4546
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4302 - val_accuracy: 0.8117 - val_loss: 0.4545
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4297 - val_accuracy: 0.8052 - val_loss: 0.4547
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4293 - val_accuracy: 0.7987 - val_loss: 0.4530
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4291 - val_accuracy: 0.7987 - val_loss: 0.4536
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4288 - val_accuracy: 0.8052 - val_loss: 0.4513
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4282 - val_accuracy: 0.7987 - val_loss: 0.4515
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4277 - val_accuracy: 0.7987 - val_loss: 0.4517
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4277 - val_accuracy: 0.8052 - val_loss: 0.4506
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4270 - val_accuracy: 0.7987 - val_loss: 0.4509
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4272 - val_accuracy: 0.8052 - val_loss: 0.4521
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4264 - val_accuracy: 0.8117 - val_loss: 0.4526
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4261 - val_accuracy: 0.8052 - val_loss: 0.4517
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4257 - val_accuracy: 0.8052 - val_loss: 0.4521
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4253 - val_accuracy: 0.8117 - val_loss: 0.4523
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4254 - val_accuracy: 0.8052 - val_loss: 0.4534
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4252 - val_accuracy: 0.8117 - val_loss: 0.4550
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4248 - val_accuracy: 0.8052 - val_loss: 0.4538
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7883 - loss: 0.4246 - val_accuracy: 0.8052 - val_loss: 0.4534
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4238 - val_accuracy: 0.8052 - val_loss: 0.4541
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4238 - val_accuracy: 0.7987 - val_loss: 0.4538
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4234 - val_accuracy: 0.7987 - val_loss: 0.4537
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4234 - val_accuracy: 0.7922 - val_loss: 0.4533
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4232 - val_accuracy: 0.7987 - val_loss: 0.4531
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4225 - val_accuracy: 0.7987 - val_loss: 0.4528
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4223 - val_accuracy: 0.7987 - val_loss: 0.4539
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4220 - val_accuracy: 0.8052 - val_loss: 0.4538
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4220 - val_accuracy: 0.8052 - val_loss: 0.4549
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4220 - val_accuracy: 0.8052 - val_loss: 0.4563
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4218 - val_accuracy: 0.8052 - val_loss: 0.4545
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4209 - val_accuracy: 0.7987 - val_loss: 0.4542
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4215 - val_accuracy: 0.8052 - val_loss: 0.4546
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4200 - val_accuracy: 0.7987 - val_loss: 0.4544
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4200 - val_accuracy: 0.8052 - val_loss: 0.4540
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4203 - val_accuracy: 0.8052 - val_loss: 0.4537
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4200 - val_accuracy: 0.7987 - val_loss: 0.4545
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4192 - val_accuracy: 0.7987 - val_loss: 0.4532
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4193 - val_accuracy: 0.7987 - val_loss: 0.4530
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4191 - val_accuracy: 0.7987 - val_loss: 0.4533
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4187 - val_accuracy: 0.8052 - val_loss: 0.4535

In [58]:
# 1. Selection of appropriate optimizer
# 2. No of nodes in a layer
# 3. how to select no. of layer
# 4. All in all one model

In [59]:
# pip install -U keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.12/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.81.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.5.20)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

**1. Selection of appropriate optimizer**

In [60]:
import kerastuner as kt

In [61]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  optimizer = hp.Choice('optimizer',values = ['adam','sgd','rmsprop','adadelta'])
  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [62]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [63]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [64]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [65]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [66]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [67]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 92ms/step - accuracy: 0.7394 - loss: 0.5515 - val_accuracy: 0.7662 - val_loss: 0.5393
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.7541 - loss: 0.5299 - val_accuracy: 0.7727 - val_loss: 0.5228
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7590 - loss: 0.5157 - val_accuracy: 0.7597 - val_loss: 0.5113
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.7590 - loss: 0.5047 - val_accuracy: 0.7597 - val_loss: 0.5043
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7638 - loss: 0.4967 - val_accuracy: 0.7727 - val_loss: 0.4975
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7671 - loss: 0.4891 - val_accuracy: 0.7727 - val_loss: 0.4939
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7785 - loss: 0.4827 - val_accuracy: 0.7792 - val_loss: 0.4899
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7818 - loss: 0.4779 - val_accuracy: 0.7792 - val_loss: 0.4869
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7818 - loss: 0.4739 - val_accuracy: 0.7727 - val_loss: 0.4853
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.7834 - loss: 0.4706 - val_accuracy: 0.7792 - val_loss: 0.4821
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.7850 - loss: 0.4675 - val_accuracy: 0.7792 - val_loss: 0.4815
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7866 - loss: 0.4645 - val_accuracy: 0.7792 - val_loss: 0.4807
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7883 - loss: 0.4624 - val_accuracy: 0.7857 - val_loss: 0.4801
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.7850 - loss: 0.4606 - val_accuracy: 0.7857 - val_loss: 0.4795
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 0.7866 - loss: 0.4589 - val_accuracy: 0.7857 - val_loss: 0.4795
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.7801 - loss: 0.4575 - val_accuracy: 0.7792 - val_loss: 0.4786
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.7883 - loss: 0.4562 - val_accuracy: 0.7792 - val_loss: 0.4779
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.7899 - loss: 0.4551 - val_accuracy: 0.7792 - val_loss: 0.4786
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.7883 - loss: 0.4540 - val_accuracy: 0.7727 - val_loss: 0.4787
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7883 - loss: 0.4532 - val_accuracy: 0.7727 - val_loss: 0.4782
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7883 - loss: 0.4523 - val_accuracy: 0.7792 - val_loss: 0.4777
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.7883 - loss: 0.4513 - val_accuracy: 0.7792 - val_loss: 0.4770
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7866 - loss: 0.4503 - val_accuracy: 0.7792 - val_loss: 0.4774
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7883 - loss: 0.4494 - val_accuracy: 0.7792 - val_loss: 0.4773
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.7850 - loss: 0.4486 - val_accuracy: 0.7727 - val_loss: 0.4758
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7866 - loss: 0.4483 - val_accuracy: 0.7792 - val_loss: 0.4763
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4474 - val_accuracy: 0.7727 - val_loss: 0.4758
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7850 - loss: 0.4468 - val_accuracy: 0.7662 - val_loss: 0.4760
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7899 - loss: 0.4460 - val_accuracy: 0.7662 - val_loss: 0.4769
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7850 - loss: 0.4456 - val_accuracy: 0.7662 - val_loss: 0.4751
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7866 - loss: 0.4451 - val_accuracy: 0.7662 - val_loss: 0.4754
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7834 - loss: 0.4445 - val_accuracy: 0.7727 - val_loss: 0.4752
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7883 - loss: 0.4437 - val_accuracy: 0.7727 - val_loss: 0.4735
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7883 - loss: 0.4430 - val_accuracy: 0.7792 - val_loss: 0.4737
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4428 - val_accuracy: 0.7727 - val_loss: 0.4741
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4422 - val_accuracy: 0.7792 - val_loss: 0.4739
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4420 - val_accuracy: 0.7792 - val_loss: 0.4735
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4414 - val_accuracy: 0.7792 - val_loss: 0.4735
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4409 - val_accuracy: 0.7857 - val_loss: 0.4736
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4408 - val_accuracy: 0.7792 - val_loss: 0.4729
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4403 - val_accuracy: 0.7922 - val_loss: 0.4736
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4398 - val_accuracy: 0.7857 - val_loss: 0.4732
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4393 - val_accuracy: 0.7792 - val_loss: 0.4743
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4389 - val_accuracy: 0.7857 - val_loss: 0.4739
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4389 - val_accuracy: 0.7727 - val_loss: 0.4738
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4383 - val_accuracy: 0.7792 - val_loss: 0.4741
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4377 - val_accuracy: 0.7857 - val_loss: 0.4734
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4374 - val_accuracy: 0.7987 - val_loss: 0.4726
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4374 - val_accuracy: 0.7792 - val_loss: 0.4729
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4366 - val_accuracy: 0.7857 - val_loss: 0.4723
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7899 - loss: 0.4366 - val_accuracy: 0.7857 - val_loss: 0.4722
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7899 - loss: 0.4362 - val_accuracy: 0.7792 - val_loss: 0.4730
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4358 - val_accuracy: 0.7792 - val_loss: 0.4730
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4355 - val_accuracy: 0.7857 - val_loss: 0.4742
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4352 - val_accuracy: 0.7857 - val_loss: 0.4755
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4348 - val_accuracy: 0.7857 - val_loss: 0.4745
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4346 - val_accuracy: 0.7857 - val_loss: 0.4743
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4342 - val_accuracy: 0.7857 - val_loss: 0.4737
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4338 - val_accuracy: 0.7857 - val_loss: 0.4742
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4338 - val_accuracy: 0.7857 - val_loss: 0.4717
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4332 - val_accuracy: 0.7857 - val_loss: 0.4722
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4326 - val_accuracy: 0.7857 - val_loss: 0.4718
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4326 - val_accuracy: 0.7922 - val_loss: 0.4706
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4322 - val_accuracy: 0.7857 - val_loss: 0.4707
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4319 - val_accuracy: 0.7857 - val_loss: 0.4709
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4316 - val_accuracy: 0.7857 - val_loss: 0.4699
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4312 - val_accuracy: 0.7987 - val_loss: 0.4679
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4310 - val_accuracy: 0.8052 - val_loss: 0.4674
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4307 - val_accuracy: 0.8052 - val_loss: 0.4673
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4303 - val_accuracy: 0.8117 - val_loss: 0.4676
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4302 - val_accuracy: 0.7987 - val_loss: 0.4690
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4298 - val_accuracy: 0.7792 - val_loss: 0.4694
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4295 - val_accuracy: 0.7922 - val_loss: 0.4708
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4295 - val_accuracy: 0.7987 - val_loss: 0.4725
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4288 - val_accuracy: 0.7922 - val_loss: 0.4726
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4288 - val_accuracy: 0.7987 - val_loss: 0.4716
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4288 - val_accuracy: 0.7922 - val_loss: 0.4703
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4283 - val_accuracy: 0.7922 - val_loss: 0.4710
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4277 - val_accuracy: 0.7922 - val_loss: 0.4704
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4278 - val_accuracy: 0.7922 - val_loss: 0.4707
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4279 - val_accuracy: 0.8182 - val_loss: 0.4691
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4276 - val_accuracy: 0.8052 - val_loss: 0.4685
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4270 - val_accuracy: 0.8052 - val_loss: 0.4690
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4265 - val_accuracy: 0.7987 - val_loss: 0.4688
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4267 - val_accuracy: 0.8052 - val_loss: 0.4683
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4264 - val_accuracy: 0.8182 - val_loss: 0.4686
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4260 - val_accuracy: 0.8117 - val_loss: 0.4691
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4259 - val_accuracy: 0.8052 - val_loss: 0.4687
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4254 - val_accuracy: 0.8052 - val_loss: 0.4689
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4253 - val_accuracy: 0.8117 - val_loss: 0.4697
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4254 - val_accuracy: 0.8117 - val_loss: 0.4697
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4249 - val_accuracy: 0.8052 - val_loss: 0.4705
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4244 - val_accuracy: 0.7987 - val_loss: 0.4713
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4242 - val_accuracy: 0.8117 - val_loss: 0.4703

**2. No of nodes in a layer**

In [70]:
def build_model(hp):
  model = Sequential()
  units = hp.Int('unitds',8,128,step=8)
  model.add(Dense(units=units,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [71]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials = 5,
                        directory = 'mydir',
                        project_name = 'Daibetes_Prediction')

In [72]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.8051947951316833

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 14s

In [73]:
tuner.results_summary()

Results summary
Results in mydir/Daibetes_Prediction
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 4 summary
Hyperparameters:
unitds: 40
Score: 0.8051947951316833

Trial 2 summary
Hyperparameters:
unitds: 80
Score: 0.7857142686843872

Trial 3 summary
Hyperparameters:
unitds: 112
Score: 0.7857142686843872

Trial 0 summary
Hyperparameters:
unitds: 96
Score: 0.7727272510528564

Trial 1 summary
Hyperparameters:
unitds: 32
Score: 0.7662337422370911

In [74]:
tuner.get_best_hyperparameters()[0].values

{'unitds': 40}

In [75]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [78]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6)

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7736 - loss: 0.4991
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7769 - loss: 0.4857
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7866 - loss: 0.4782
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7801 - loss: 0.4722
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7801 - loss: 0.4681
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7785 - loss: 0.4642
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7801 - loss: 0.4611
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7801 - loss: 0.4583
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7752 - loss: 0.4562
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7818 - loss: 0.4544
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7850 - loss: 0.4527
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7801 - loss: 0.4514
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7818 - loss: 0.4503
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7818 - loss: 0.4489
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7834 - loss: 0.4483
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7769 - loss: 0.4470
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7866 - loss: 0.4457
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7834 - loss: 0.4448
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7834 - loss: 0.4445
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7883 - loss: 0.4430
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7834 - loss: 0.4425
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7834 - loss: 0.4417
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7834 - loss: 0.4416
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7866 - loss: 0.4404
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7818 - loss: 0.4400
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7850 - loss: 0.4393
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7883 - loss: 0.4388
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7866 - loss: 0.4378
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7866 - loss: 0.4371
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7850 - loss: 0.4362
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7883 - loss: 0.4358
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7866 - loss: 0.4352
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7899 - loss: 0.4350
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7866 - loss: 0.4339
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7883 - loss: 0.4332
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7915 - loss: 0.4325
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7915 - loss: 0.4327
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7915 - loss: 0.4317
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7883 - loss: 0.4312
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7948 - loss: 0.4308
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7899 - loss: 0.4302
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7883 - loss: 0.4299
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7915 - loss: 0.4292
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7915 - loss: 0.4287
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7915 - loss: 0.4279
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7866 - loss: 0.4281
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7915 - loss: 0.4273
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7932 - loss: 0.4267
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7899 - loss: 0.4262
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7883 - loss: 0.4257
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7866 - loss: 0.4258
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7932 - loss: 0.4250
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4246
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4247
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4236
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4234
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4229
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4225
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4219
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4217
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4206
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4211
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4208
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4200
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4198
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4191
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4189
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4185
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4185
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4180
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4169
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7964 - loss: 0.4172
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7964 - loss: 0.4168
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8062 - loss: 0.4164
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4161
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7964 - loss: 0.4157
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8029 - loss: 0.4150
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8029 - loss: 0.4144
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8062 - loss: 0.4142
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8029 - loss: 0.4139
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8013 - loss: 0.4136
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8029 - loss: 0.4132
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8046 - loss: 0.4133
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8013 - loss: 0.4125
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8013 - loss: 0.4119
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8062 - loss: 0.4119
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8078 - loss: 0.4115
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8111 - loss: 0.4112
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8111 - loss: 0.4109
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8111 - loss: 0.4105
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8094 - loss: 0.4108
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8094 - loss: 0.4099
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8046 - loss: 0.4098
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8062 - loss: 0.4098

**Selection of no of layers**

In [95]:
def build_model(hp):
    model = Sequential()

    model.add(Dense(
        72,
        activation='relu',
        input_shape=(X_train.shape[1],)
    ))

    for i in range(hp.Int('num_layers', 1, 10)):
        model.add(Dense(72, activation='relu'))

    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer='rmsprop',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [100]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=3,
    directory='mydir',
    project_name='num_layers'
)

tuner.search(
    X_train,
    y_train,
    epochs=3,
    validation_data=(X_test, y_test)
)

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.8051947951316833

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 10s

In [102]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [99]:
import shutil

shutil.rmtree('mydir', ignore_errors=True)

In [101]:
tuner.results_summary()

Results summary
Results in mydir/num_layers
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 1 summary
Hyperparameters:
num_layers: 3
Score: 0.8116883039474487

Trial 0 summary
Hyperparameters:
num_layers: 4
Score: 0.8051947951316833

Trial 2 summary
Hyperparameters:
num_layers: 2
Score: 0.8051947951316833

In [103]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3}

In [105]:
model  = tuner.get_best_models(num_models=1)[0]

In [106]:
model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - accuracy: 0.7736 - loss: 0.4657 - val_accuracy: 0.8182 - val_loss: 0.4626
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8013 - loss: 0.4465 - val_accuracy: 0.7857 - val_loss: 0.4776
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4327 - val_accuracy: 0.7922 - val_loss: 0.4996
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4336 - val_accuracy: 0.7662 - val_loss: 0.4657
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4229 - val_accuracy: 0.7727 - val_loss: 0.4769
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4183 - val_accuracy: 0.7922 - val_loss: 0.4740
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4083 - val_accuracy: 0.7727 - val_loss: 0.4752
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4016 - val_accuracy: 0.7727 - val_loss: 0.4746
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3970 - val_accuracy: 0.7987 - val_loss: 0.4691
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3908 - val_accuracy: 0.7532 - val_loss: 0.5210
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3858 - val_accuracy: 0.8052 - val_loss: 0.4679
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3725 - val_accuracy: 0.7922 - val_loss: 0.4946
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3788 - val_accuracy: 0.7792 - val_loss: 0.4822
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3656 - val_accuracy: 0.7987 - val_loss: 0.4818
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3644 - val_accuracy: 0.7792 - val_loss: 0.5012
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3539 - val_accuracy: 0.7922 - val_loss: 0.5139
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3556 - val_accuracy: 0.7987 - val_loss: 0.4940
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8485 - loss: 0.3330 - val_accuracy: 0.8117 - val_loss: 0.4919
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8518 - loss: 0.3310 - val_accuracy: 0.8117 - val_loss: 0.4958
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8534 - loss: 0.3261 - val_accuracy: 0.7662 - val_loss: 0.5085
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8550 - loss: 0.3124 - val_accuracy: 0.7727 - val_loss: 0.5214
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8713 - loss: 0.3069 - val_accuracy: 0.8247 - val_loss: 0.5151
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8632 - loss: 0.3047 - val_accuracy: 0.7987 - val_loss: 0.5144
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8762 - loss: 0.2942 - val_accuracy: 0.7987 - val_loss: 0.5382
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8762 - loss: 0.2884 - val_accuracy: 0.7987 - val_loss: 0.5544
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8925 - loss: 0.2828 - val_accuracy: 0.7792 - val_loss: 0.5865
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8958 - loss: 0.2765 - val_accuracy: 0.7857 - val_loss: 0.6455
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8974 - loss: 0.2620 - val_accuracy: 0.7727 - val_loss: 0.6469
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2553 - val_accuracy: 0.7857 - val_loss: 0.6294
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9104 - loss: 0.2399 - val_accuracy: 0.7338 - val_loss: 0.6287
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9104 - loss: 0.2391 - val_accuracy: 0.7468 - val_loss: 0.6320
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2349 - val_accuracy: 0.7857 - val_loss: 0.6476
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9169 - loss: 0.2255 - val_accuracy: 0.7597 - val_loss: 0.6966
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9137 - loss: 0.2178 - val_accuracy: 0.7338 - val_loss: 0.7045
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9153 - loss: 0.2194 - val_accuracy: 0.7532 - val_loss: 0.7050
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9267 - loss: 0.1938 - val_accuracy: 0.7662 - val_loss: 0.6638
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9349 - loss: 0.1976 - val_accuracy: 0.7792 - val_loss: 0.6928
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9218 - loss: 0.1962 - val_accuracy: 0.7208 - val_loss: 0.7675
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9316 - loss: 0.1877 - val_accuracy: 0.7662 - val_loss: 0.7407
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9397 - loss: 0.1706 - val_accuracy: 0.7338 - val_loss: 0.7971
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9365 - loss: 0.1652 - val_accuracy: 0.7662 - val_loss: 0.8618
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9349 - loss: 0.1583 - val_accuracy: 0.7208 - val_loss: 1.0011
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9397 - loss: 0.1579 - val_accuracy: 0.7597 - val_loss: 0.8221
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9511 - loss: 0.1455 - val_accuracy: 0.7403 - val_loss: 0.8762
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9593 - loss: 0.1363 - val_accuracy: 0.7727 - val_loss: 0.9142
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9430 - loss: 0.1480 - val_accuracy: 0.7273 - val_loss: 1.1708
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1200 - val_accuracy: 0.7532 - val_loss: 0.9566
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9609 - loss: 0.1140 - val_accuracy: 0.7273 - val_loss: 1.1892
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.1060 - val_accuracy: 0.7662 - val_loss: 1.0361
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9593 - loss: 0.1210 - val_accuracy: 0.7208 - val_loss: 1.0179
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0930 - val_accuracy: 0.7078 - val_loss: 1.4217
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1049 - val_accuracy: 0.7208 - val_loss: 1.1271
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9642 - loss: 0.0991 - val_accuracy: 0.6948 - val_loss: 1.0911
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9577 - loss: 0.1081 - val_accuracy: 0.7338 - val_loss: 1.1684
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0784 - val_accuracy: 0.7662 - val_loss: 1.1526
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9642 - loss: 0.0966 - val_accuracy: 0.7338 - val_loss: 1.1564
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0785 - val_accuracy: 0.7338 - val_loss: 1.3334
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0766 - val_accuracy: 0.7532 - val_loss: 1.2599
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0985 - val_accuracy: 0.7273 - val_loss: 1.2165
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0612 - val_accuracy: 0.7338 - val_loss: 1.3404
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0682 - val_accuracy: 0.7597 - val_loss: 1.2880
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9821 - loss: 0.0710 - val_accuracy: 0.7532 - val_loss: 1.2955
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0558 - val_accuracy: 0.7143 - val_loss: 1.4368
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0616 - val_accuracy: 0.7143 - val_loss: 1.3883
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0554 - val_accuracy: 0.7403 - val_loss: 1.4709
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0548 - val_accuracy: 0.6883 - val_loss: 1.7108
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0505 - val_accuracy: 0.7403 - val_loss: 1.5123
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0535 - val_accuracy: 0.7078 - val_loss: 1.7947
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0358 - val_accuracy: 0.7143 - val_loss: 1.8509
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0448 - val_accuracy: 0.7013 - val_loss: 1.9004
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0469 - val_accuracy: 0.7338 - val_loss: 1.6430
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0474 - val_accuracy: 0.7338 - val_loss: 1.7741
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0392 - val_accuracy: 0.7273 - val_loss: 1.7569
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0366 - val_accuracy: 0.7078 - val_loss: 1.9885
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9853 - loss: 0.0517 - val_accuracy: 0.7078 - val_loss: 1.8414
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0384 - val_accuracy: 0.7338 - val_loss: 2.3055
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0392 - val_accuracy: 0.7338 - val_loss: 1.8123
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0231 - val_accuracy: 0.7403 - val_loss: 1.8975
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0596 - val_accuracy: 0.7468 - val_loss: 1.8568
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0352 - val_accuracy: 0.7143 - val_loss: 2.0342
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9902 - loss: 0.0354 - val_accuracy: 0.7403 - val_loss: 2.0120
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0367 - val_accuracy: 0.7273 - val_loss: 2.2578
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0375 - val_accuracy: 0.7143 - val_loss: 1.9356
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0252 - val_accuracy: 0.7208 - val_loss: 2.1424
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0380 - val_accuracy: 0.7013 - val_loss: 2.0107
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0143 - val_accuracy: 0.6883 - val_loss: 2.2725
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0237 - val_accuracy: 0.7013 - val_loss: 2.2880
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0246 - val_accuracy: 0.6883 - val_loss: 2.1273
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9837 - loss: 0.0405 - val_accuracy: 0.7143 - val_loss: 2.1015
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0262 - val_accuracy: 0.6818 - val_loss: 2.4988
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0367 - val_accuracy: 0.7143 - val_loss: 2.2793
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9935 - loss: 0.0205 - val_accuracy: 0.7208 - val_loss: 2.1634
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9870 - loss: 0.0337 - val_accuracy: 0.7078 - val_loss: 2.2880
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9935 - loss: 0.0234 - val_accuracy: 0.7403 - val_loss: 2.1718

In [109]:
def build_model(hp):
  model = Sequential()
  counter = 0
  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    if counter == 0:
      model.add(
          Dense(
              hp.Int('units'+str(i), min_value=8, max_value=128, step=8),
              activation=hp.Choice('activation'+ str(i),values=['relu','tanh','sigmoid']),
              input_dim=8
              )
          )
    else :
     model.add(
          Dense(
              hp.Int('units'+str(i), min_value=8, max_value=128, step=8),
              activation=hp.Choice('activation'+ str(i),values=['relu','tanh','sigmoid'])
              )
          )
     counter+=1

  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values = ['rmsprop','adam','sgd','nadam','adadelta']),
                loss = 'binary_crossentropy',
                metrics=['accuracy'])
  return model

In [111]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials = 3,
                        directory = 'mydir',
                        project_name='final')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [112]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 07s]
val_accuracy: 0.8116883039474487

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 17s

In [113]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 10,
 'units0': 56,
 'activation0': 'relu',
 'optimizer': 'nadam',
 'units1': 24,
 'activation1': 'tanh',
 'units2': 120,
 'activation2': 'relu',
 'units3': 40,
 'activation3': 'sigmoid',
 'units4': 56,
 'activation4': 'relu',
 'units5': 72,
 'activation5': 'relu',
 'units6': 16,
 'activation6': 'relu',
 'units7': 112,
 'activation7': 'sigmoid',
 'units8': 96,
 'activation8': 'relu',
 'units9': 104,
 'activation9': 'relu'}

In [114]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'nadam', because it has 2 variables whereas the saved optimizer has 47 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [115]:
model.fit(X_train,y_train,epochs=200,initial_epoch=5,validation_data=(X_test,y_test))

Epoch 6/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - accuracy: 0.7785 - loss: 0.4718 - val_accuracy: 0.7792 - val_loss: 0.4720
Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4649 - val_accuracy: 0.7727 - val_loss: 0.4893
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7736 - loss: 0.4679 - val_accuracy: 0.8052 - val_loss: 0.4654
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4537 - val_accuracy: 0.7922 - val_loss: 0.4594
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.4558 - val_accuracy: 0.7662 - val_loss: 0.4805
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4572 - val_accuracy: 0.7922 - val_loss: 0.4598
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4448 - val_accuracy: 0.7987 - val_loss: 0.4571
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4331 - val_accuracy: 0.7792 - val_loss: 0.4924
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4400 - val_accuracy: 0.7857 - val_loss: 0.4567
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4285 - val_accuracy: 0.7922 - val_loss: 0.4589
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.4208 - val_accuracy: 0.6883 - val_loss: 0.5833
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7736 - loss: 0.4710 - val_accuracy: 0.7987 - val_loss: 0.4508
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8127 - loss: 0.4135 - val_accuracy: 0.7987 - val_loss: 0.4489
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8192 - loss: 0.4135 - val_accuracy: 0.7987 - val_loss: 0.4575
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8143 - loss: 0.4022 - val_accuracy: 0.7792 - val_loss: 0.4812
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.4124 - val_accuracy: 0.8052 - val_loss: 0.4551
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8127 - loss: 0.3989 - val_accuracy: 0.7857 - val_loss: 0.4736
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8192 - loss: 0.3979 - val_accuracy: 0.7857 - val_loss: 0.4620
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8355 - loss: 0.3832 - val_accuracy: 0.7792 - val_loss: 0.5001
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8339 - loss: 0.4001 - val_accuracy: 0.7922 - val_loss: 0.4756
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8404 - loss: 0.3790 - val_accuracy: 0.7987 - val_loss: 0.4751
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8420 - loss: 0.3758 - val_accuracy: 0.7922 - val_loss: 0.4808
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8355 - loss: 0.3723 - val_accuracy: 0.7987 - val_loss: 0.4744
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8339 - loss: 0.3722 - val_accuracy: 0.7922 - val_loss: 0.4754
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8567 - loss: 0.3526 - val_accuracy: 0.8182 - val_loss: 0.4757
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8469 - loss: 0.3615 - val_accuracy: 0.7922 - val_loss: 0.4873
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8648 - loss: 0.3496 - val_accuracy: 0.7857 - val_loss: 0.4839
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8632 - loss: 0.3406 - val_accuracy: 0.7662 - val_loss: 0.5117
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8746 - loss: 0.3310 - val_accuracy: 0.7857 - val_loss: 0.5053
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8925 - loss: 0.3139 - val_accuracy: 0.7597 - val_loss: 0.5103
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8827 - loss: 0.3132 - val_accuracy: 0.7532 - val_loss: 0.5790
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.3202 - val_accuracy: 0.7727 - val_loss: 0.5172
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8795 - loss: 0.3126 - val_accuracy: 0.7857 - val_loss: 0.5105
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8990 - loss: 0.2862 - val_accuracy: 0.7662 - val_loss: 0.5458
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.2673 - val_accuracy: 0.7468 - val_loss: 0.5682
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8941 - loss: 0.3031 - val_accuracy: 0.7922 - val_loss: 0.5027
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.2931 - val_accuracy: 0.7273 - val_loss: 0.5826
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9169 - loss: 0.2574 - val_accuracy: 0.7532 - val_loss: 0.7371
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8844 - loss: 0.2979 - val_accuracy: 0.7532 - val_loss: 0.5904
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9218 - loss: 0.2500 - val_accuracy: 0.7662 - val_loss: 0.5571
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9202 - loss: 0.2351 - val_accuracy: 0.7143 - val_loss: 0.6899
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9121 - loss: 0.2570 - val_accuracy: 0.8052 - val_loss: 0.5821
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9218 - loss: 0.2215 - val_accuracy: 0.7662 - val_loss: 0.5955
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9332 - loss: 0.2159 - val_accuracy: 0.7532 - val_loss: 0.6443
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9381 - loss: 0.2128 - val_accuracy: 0.7532 - val_loss: 0.6573
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9397 - loss: 0.1964 - val_accuracy: 0.7727 - val_loss: 0.6415
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9365 - loss: 0.2148 - val_accuracy: 0.7403 - val_loss: 0.6873
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9349 - loss: 0.2108 - val_accuracy: 0.7662 - val_loss: 0.6224
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9414 - loss: 0.1985 - val_accuracy: 0.7922 - val_loss: 0.6502
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9072 - loss: 0.2738 - val_accuracy: 0.7662 - val_loss: 0.5794
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9202 - loss: 0.2348 - val_accuracy: 0.7662 - val_loss: 0.5833
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9414 - loss: 0.2081 - val_accuracy: 0.7532 - val_loss: 0.6728
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9479 - loss: 0.1860 - val_accuracy: 0.7597 - val_loss: 0.7030
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9332 - loss: 0.2020 - val_accuracy: 0.7532 - val_loss: 0.7136
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9397 - loss: 0.2033 - val_accuracy: 0.7727 - val_loss: 0.6594
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9544 - loss: 0.1838 - val_accuracy: 0.7662 - val_loss: 0.6710
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9560 - loss: 0.1749 - val_accuracy: 0.7727 - val_loss: 0.6407
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9528 - loss: 0.1721 - val_accuracy: 0.7857 - val_loss: 0.6357
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9430 - loss: 0.1918 - val_accuracy: 0.7273 - val_loss: 0.7369
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9577 - loss: 0.1670 - val_accuracy: 0.7597 - val_loss: 0.6465
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9544 - loss: 0.1678 - val_accuracy: 0.7597 - val_loss: 0.7377
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9577 - loss: 0.1597 - val_accuracy: 0.7987 - val_loss: 0.6924
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9577 - loss: 0.1640 - val_accuracy: 0.7532 - val_loss: 0.7608
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9577 - loss: 0.1541 - val_accuracy: 0.7662 - val_loss: 0.8042
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8469 - loss: 0.4222 - val_accuracy: 0.7857 - val_loss: 0.4944
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8664 - loss: 0.3377 - val_accuracy: 0.7857 - val_loss: 0.5492
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9235 - loss: 0.2335 - val_accuracy: 0.7532 - val_loss: 0.6652
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9495 - loss: 0.1925 - val_accuracy: 0.7597 - val_loss: 0.7146
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9609 - loss: 0.1684 - val_accuracy: 0.7338 - val_loss: 0.7503
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9642 - loss: 0.1568 - val_accuracy: 0.7403 - val_loss: 0.7275
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9658 - loss: 0.1502 - val_accuracy: 0.7403 - val_loss: 0.7453
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9658 - loss: 0.1421 - val_accuracy: 0.7792 - val_loss: 0.7638
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9511 - loss: 0.1718 - val_accuracy: 0.7468 - val_loss: 0.7584
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9479 - loss: 0.1721 - val_accuracy: 0.7662 - val_loss: 0.7425
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9560 - loss: 0.1691 - val_accuracy: 0.7532 - val_loss: 0.7341
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9625 - loss: 0.1497 - val_accuracy: 0.7273 - val_loss: 0.8633
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9609 - loss: 0.1477 - val_accuracy: 0.7403 - val_loss: 0.7835
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9593 - loss: 0.1520 - val_accuracy: 0.6688 - val_loss: 0.9626
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9251 - loss: 0.2241 - val_accuracy: 0.7468 - val_loss: 0.7199
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9642 - loss: 0.1463 - val_accuracy: 0.7273 - val_loss: 0.8364
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9625 - loss: 0.1451 - val_accuracy: 0.7338 - val_loss: 0.8175
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9707 - loss: 0.1283 - val_accuracy: 0.7532 - val_loss: 0.8066
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9691 - loss: 0.1283 - val_accuracy: 0.7403 - val_loss: 0.8542
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9707 - loss: 0.1220 - val_accuracy: 0.7532 - val_loss: 0.8239
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9707 - loss: 0.1204 - val_accuracy: 0.7273 - val_loss: 0.8943
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9723 - loss: 0.1167 - val_accuracy: 0.7597 - val_loss: 0.8318
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9609 - loss: 0.1387 - val_accuracy: 0.7208 - val_loss: 0.9911
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9528 - loss: 0.1465 - val_accuracy: 0.7338 - val_loss: 0.9118
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9300 - loss: 0.2321 - val_accuracy: 0.8117 - val_loss: 0.6822
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9121 - loss: 0.2648 - val_accuracy: 0.7922 - val_loss: 0.5785
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9104 - loss: 0.2622 - val_accuracy: 0.7727 - val_loss: 0.5813
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9381 - loss: 0.2014 - val_accuracy: 0.7662 - val_loss: 0.6875
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9544 - loss: 0.1540 - val_accuracy: 0.7403 - val_loss: 0.8435
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9642 - loss: 0.1316 - val_accuracy: 0.7468 - val_loss: 0.8568
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9674 - loss: 0.1202 - val_accuracy: 0.7468 - val_loss: 0.8685
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9707 - loss: 0.1169 - val_accuracy: 0.7078 - val_loss: 1.1110
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9169 - loss: 0.2602 - val_accuracy: 0.7597 - val_loss: 0.6726
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9332 - loss: 0.2058 - val_accuracy: 0.7792 - val_loss: 0.6466
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9577 - loss: 0.1540 - val_accuracy: 0.7403 - val_loss: 0.7531
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9577 - loss: 0.1489 - val_accuracy: 0.7922 - val_loss: 0.7481
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9625 - loss: 0.1355 - val_accuracy: 0.7532 - val_loss: 0.8122
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9691 - loss: 0.1171 - val_accuracy: 0.7338 - val_loss: 0.9032
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9658 - loss: 0.1304 - val_accuracy: 0.7273 - val_loss: 0.9530
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9658 - loss: 0.1228 - val_accuracy: 0.7727 - val_loss: 0.8833
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9609 - loss: 0.1349 - val_accuracy: 0.7403 - val_loss: 0.8964
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9674 - loss: 0.1225 - val_accuracy: 0.7597 - val_loss: 0.8291
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9658 - loss: 0.1294 - val_accuracy: 0.7662 - val_loss: 0.7987
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9691 - loss: 0.1208 - val_accuracy: 0.7727 - val_loss: 0.8337
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9609 - loss: 0.1435 - val_accuracy: 0.7468 - val_loss: 0.8885
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9593 - loss: 0.1428 - val_accuracy: 0.7597 - val_loss: 0.8135
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9674 - loss: 0.1229 - val_accuracy: 0.7597 - val_loss: 0.9014
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9658 - loss: 0.1166 - val_accuracy: 0.7792 - val_loss: 0.8751
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9642 - loss: 0.1357 - val_accuracy: 0.7857 - val_loss: 0.8078
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9691 - loss: 0.1182 - val_accuracy: 0.7792 - val_loss: 0.8699
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9707 - loss: 0.1130 - val_accuracy: 0.7662 - val_loss: 0.8734
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9723 - loss: 0.1072 - val_accuracy: 0.7662 - val_loss: 0.9448
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9723 - loss: 0.1026 - val_accuracy: 0.7532 - val_loss: 1.0063
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9691 - loss: 0.1111 - val_accuracy: 0.7532 - val_loss: 0.9887
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9739 - loss: 0.0978 - val_accuracy: 0.7792 - val_loss: 0.9213
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9707 - loss: 0.1000 - val_accuracy: 0.7792 - val_loss: 0.9253
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9674 - loss: 0.1062 - val_accuracy: 0.7727 - val_loss: 0.9197
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9707 - loss: 0.1046 - val_accuracy: 0.7922 - val_loss: 0.8772
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9707 - loss: 0.1131 - val_accuracy: 0.7468 - val_loss: 0.9662
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9642 - loss: 0.1133 - val_accuracy: 0.6883 - val_loss: 1.5648
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9235 - loss: 0.2414 - val_accuracy: 0.7792 - val_loss: 0.6985
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9446 - loss: 0.1816 - val_accuracy: 0.7532 - val_loss: 0.7623
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9560 - loss: 0.1421 - val_accuracy: 0.7857 - val_loss: 0.7767
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9625 - loss: 0.1223 - val_accuracy: 0.7403 - val_loss: 0.9469
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9658 - loss: 0.1127 - val_accuracy: 0.7662 - val_loss: 0.9412
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9739 - loss: 0.0963 - val_accuracy: 0.7662 - val_loss: 1.0156
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9707 - loss: 0.0984 - val_accuracy: 0.7662 - val_loss: 0.9476
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9707 - loss: 0.0961 - val_accuracy: 0.7922 - val_loss: 0.9694
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9625 - loss: 0.1310 - val_accuracy: 0.7662 - val_loss: 1.0108
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9609 - loss: 0.1144 - val_accuracy: 0.7987 - val_loss: 0.8301
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9609 - loss: 0.1189 - val_accuracy: 0.7922 - val_loss: 0.7828
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9674 - loss: 0.1104 - val_accuracy: 0.7727 - val_loss: 0.8971
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9691 - loss: 0.1055 - val_accuracy: 0.7727 - val_loss: 0.9389
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9414 - loss: 0.2070 - val_accuracy: 0.7338 - val_loss: 0.8988
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9381 - loss: 0.1823 - val_accuracy: 0.7727 - val_loss: 0.7761
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9609 - loss: 0.1275 - val_accuracy: 0.7792 - val_loss: 0.8309
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9691 - loss: 0.1048 - val_accuracy: 0.7792 - val_loss: 0.8691
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9691 - loss: 0.0957 - val_accuracy: 0.7468 - val_loss: 0.9685
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9723 - loss: 0.0918 - val_accuracy: 0.7597 - val_loss: 1.0227
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9707 - loss: 0.0961 - val_accuracy: 0.7597 - val_loss: 0.9496
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9723 - loss: 0.0912 - val_accuracy: 0.7662 - val_loss: 1.0430
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9739 - loss: 0.0847 - val_accuracy: 0.7727 - val_loss: 0.9580
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9739 - loss: 0.0872 - val_accuracy: 0.7792 - val_loss: 0.9156
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9739 - loss: 0.0812 - val_accuracy: 0.7662 - val_loss: 1.0484
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9739 - loss: 0.0807 - val_accuracy: 0.7662 - val_loss: 1.1165
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9739 - loss: 0.0805 - val_accuracy: 0.7792 - val_loss: 1.0678
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9739 - loss: 0.0792 - val_accuracy: 0.7662 - val_loss: 1.1139
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9739 - loss: 0.0784 - val_accuracy: 0.7727 - val_loss: 1.1333
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9739 - loss: 0.0755 - val_accuracy: 0.7727 - val_loss: 1.2026
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9739 - loss: 0.0768 - val_accuracy: 0.7727 - val_loss: 1.1606
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9739 - loss: 0.0747 - val_accuracy: 0.7662 - val_loss: 1.2643
Epoch 161/200